### ISSUE TITLE
Coloring is weird for Manual Feedback Scoring Details

### ISSUE THREAD

**Issue by nuTNR** [CodeGrade/bottlenose#104]
When you give a -0 on a info, warning, or error comment, the background is red, just like if you give a deduction:

![image](https://user-images.githubusercontent.com/15700846/45783274-529a5480-bc33-11e8-8379-8586b630e393.png)

It ideally would be be a neutral color like the +0 on a bonus comment, or not have the number at all:

![image](https://user-images.githubusercontent.com/15700846/45783385-a3aa4880-bc33-11e8-9961-fb0ce098fe63.png)

**Comment by dmelcer9** [comment]
I just realized I opened the issue on the wrong account, whoops.

**Comment by blerner** [comment]
Green means extra credit. Everything else is critique, either error, warning or informational, including zero point critiques, which mean "we aren't penalizing you, but this is a mistake worth fixing I'm the future."
