### ISSUE TITLE
NoMethodError on creating registration requests

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/bottlenose#106]
I get a `NoMethodError` when submitting a registration request.

```
NoMethodError - undefined method `match?' for "1":String
Did you mean?  match:
  app/models/reg_request.rb:35:in `block in confirm_sections'
  app/models/reg_request.rb:32:in `confirm_sections'
  app/controllers/reg_requests_controller.rb:18:in `create'
```

https://github.com/CodeGrade/bottlenose/blob/ffbae6eec4e507fb50a5de74e10e0d7e04f9f211/app/models/reg_request.rb#L35-L36

Should both instances of `match?` be `match`?

**Comment by blerner** [comment]
I don't understand why you're getting that -- what version of ruby are you running, and why does it appear to work for me?

**Comment by kylesferrazza** [comment]
Not sure - I am running ruby 2.3.7.

I can only find `match` without the `?` in `String`.
https://ruby-doc.org/core-2.2.0/String.html#method-i-match

**Comment by kylesferrazza** [comment]
Looks like it was introduced in 2.5.1

https://ruby-doc.org/core-2.5.1/Regexp.html#method-i-match-3F
