### ISSUE TITLE
Some profile pictures are sideways in the hover view

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/bottlenose#107]
For example, see the second student in this submission:
https://handins.ccs.neu.edu/courses/40/teamsets/470/teams/16075

Their picture is the proper orientation (open it in a new tab and it faces the right way), but on hover, is rotated counterclockwise 90 degrees.

**Comment by kylesferrazza** [comment]
This seems to be fixed by https://github.com/blerner/bottlenose/commit/56be20e965a26e602286ddf49fe65cdd8028ef79

**Comment by blerner** [comment]
Closing for now; if we see it as a problem again, we can reopen.
