### ISSUE TITLE
Redirect to intended page after login

### ISSUE THREAD

**Issue by dbp** [CodeGrade/bottlenose#112]
If you aren't logged in and go to a link, you get redirected to a login page. It would be nice if, after logging in, you were redirected back to where you were going originally.

**Comment by blerner** [comment]
I'm not sure I have control over this, or at least, I don't know enough about Rails/Devise login flows to get it working...

**Comment by kylesferrazza** [comment]
@blerner I got this working with Devise in another project I was working on. I'll look into adding it here
