### ISSUE TITLE
Make it easier to view a students entire grading profile as a professor

### ISSUE THREAD

**Issue by dbp** [CodeGrade/bottlenose#113]
Right now, as far as I can tell, I have to impersonate a student in order to see all their grades together. It would be nice if the view of the profile, as a professor, would have that info on it, as frequently I want to look through a bunch of students in sequence, and it's somewhat error-prone to be swapping between impersonations.

**Comment by blerner** [comment]
This is actually quite easy: go to the Assignments page, scroll to the students grade table, and click on the row.  It'll expand to show a trendline graph of student performance vs class average performance.  You can click on individual points in the graph to jump straight to their submissions, too.

**Comment by dbp** [comment]
Oh! Magic! I had clicked on their _names_ before, but that impersonates them :) I hadn't clicked on the row elsewhere... Closing :)

**Comment by blerner** [comment]
I have screenshots to incorporate into the documentation, but haven't had time to write it all up yet...

**Comment by dbp** [comment]
Though it actually doesn't have all the assignments (e.g., it's missing our Exam 1, though it has assignments before and after it... it does have our Exam 0 though).

**Comment by blerner** [comment]
It's there, between "Week 7 Set a" and "Week 7 Set b".  There isn't enough room on the axis to label every assignment, but they're all shown in chronological order by due date.
