### ISSUE TITLE
Edit Assignment button unclickable on iOS

### ISSUE THREAD

**Issue by dbp** [CodeGrade/bottlenose#128]
This may affect other mobile, but I’m testing on an iPhone 7, iOS12

On the assignment page, the edit assignment button (and the one next to it) are not clickable; something is overlapping them, probably. This happens in portrait and landscape mode on the phone (even while the page layout changes, this behavior remains the same).

**Comment by blerner** [comment]
This is a z-index issue that I've seen before. It's annoying, but shouldn't be super hard to fix.
