### ISSUE TITLE
Add conflict-of-interest tracking between graders and students

### ISSUE THREAD

**Issue by blerner** [CodeGrade/bottlenose#131]
Currently, the instructors have to manually keep track of which staff graders are prohibited from grading particular students.  This is fine when the course is small, but it gets prohibitively complicated when the course grows.

If we can store conflict-of-interest pairings in the database, then we can automatically compute a random assignment of staff graders to submissions using a fairly standard max-flow algorithm: a 1-unit edge connects submissions to graders iff the grader is not conflicted with anyone in the submission's team; a 1-unit edge connects the source to each submission, and each grader is connected to the sink by an edge with weight proportional to their intended workload.  Once max-flow completes, if every submission has a nonzero flow through it, then it has been allocated to a grader, and no grader can be allocated more than their fair share of work.

I've implemented the push-relabel max-flow algorithm already; this just needs UI for managing the conflicts, and wiring up the max-flow code into `GraderAllocationsController#compute_who_grades`.

**Comment by williams-jack** [comment]
Closed with PR #227
