### ISSUE TITLE
Searching for Students by Username

### ISSUE THREAD

**Issue by grobalex** [CodeGrade/bottlenose#137]
Feature Request:

Currently there is no way to lookup students by their Username instead the current workflow is to go to the student facebook of a particular course and search by their name. 

Possible Implementation:
In the course page to the right of the sub navigation, add a search box only visible to professors that allows the look up of students by username. If found it should direct to the users profile.

**Comment by grobalex** [comment]
I wonder if this feature could just add an addition to the student facebook. Currently it shows the student name and nickname if it exists. We could display the username on a line below? The user could do a quick cmd/ctrl + f but this feels more hacky?

**Comment by blerner** [comment]
I think this is largely fixed by the above PR.  Closing for now; we can reopen if other pages need to search by username.
