### ISSUE TITLE
Missing Keyboard Shortcuts

### ISSUE THREAD

**Issue by jakeisnt** [CodeGrade/bottlenose#171]
As a grader, having shortcuts available during the grading process to:
- jump to a specific line in code
- jump to a new file in the file browser
-open up a comment box
-designate a comment as an error, warning, info or bonus
-save and complete an assignment
would make the grading process a bit faster.

**Comment by blerner** [comment]
This is very hard to do in a cross-browser, cross-OS way, since there aren't many keypresses available that don't already have some meaning somewhere.

You _can_ navigate through the file browser with the arrow keys, and even that is unfortunately fiddly depending on the browser.
