### ISSUE TITLE
Administer Grading / Deduction Guidelines

### ISSUE THREAD

**Issue by jakeisnt** [CodeGrade/bottlenose#172]
Currently, it's entirely possible to award points to assignments - or deduct from assignments - regardless of whether the associated comment is an 'info', 'error', 'warning' or 'bonus'. This can lead to unnecessary mistakes and typos during the grading process. 

While the system as a whole should not administer rules for what sorts of comments can be deductions or bonus allocations, instructors should be able to administer these policies on a per-course basis - e.g. allowing the instructor of a course to add of a rule ensuring that 'info' comments cannot have an associated point value.

**Comment by blerner** [comment]
Not sure I understand this comment.  Error, Warning and Info comments can all have associated deductions; Bonus comments can have associated rewards.  "Error", "Warning" and "Info" are just commentary about how conceptually severe the mistake is, not rubric-based commentary on how much the grading penalty is.
