### ISSUE TITLE
Notify partner when teammate submits assignment

### ISSUE THREAD

**Issue by beenbiishop** [CodeGrade/bottlenose#215]
It would be really nice if an email or text message was sent to the other members of a team when a teammate submits an assignment. Let's say there was a partner dispute, and a partner submits the agreed-upon code, but the other partner logs on last minute and submits another file. A notification email would be triggered to the group every time someone makes a submission, ensuring everyone is in the loop.

**Comment by blerner** [comment]
This one isn't really necessary.  If one partner attempts to submit without the other partner knowing, and the second partner disputes it, the professor can always retroactively split the partnership, resubmit on behalf of the aggrieved student, and individually grade both students.  Adding this sort of notification would require adding the ability to send emails, which adds a very large attack surface (see #216) that I'm very, very hesitant to add.
