### ISSUE TITLE
Assignment almost due warning

### ISSUE THREAD

**Issue by beenbiishop** [CodeGrade/bottlenose#216]
It would be really nice if a professor could set up warning emails for when an assignment is almost due - e.g. 24 hours and 8 hours - that is automatically sent if a student has not submitted any files.

Here's an example email:

**Subject: Your [AssignmentName] Assignment is Almost Due**
Dear [FirstName],

Your assignment, [AssignmentName] is due in [TimeLeft] on [Date/TimeDue].

Make sure to submit your response at the link below before the deadline.
[AssignmentLink]

If you do not submit your assignment on time, our late policy is:
[LatePolicy]

Please reach out to your professor, [ProfessorName], with any questions or concerns.

Sincerely,
[ProfessorName]

**Comment by blerner** [comment]
I'm extremely hesitant to enable any sort of email capability to Bottlenose: it requires granting the server the permission to send emails, which adds a very large potential attack surface.  I'm inclined to mark this #wontfix, unless it's urgently and compellingly needed.
