### ISSUE TITLE
Build an assignments-interlock mechanism

### ISSUE THREAD

**Issue by NatTuck** [CodeGrade/bottlenose#22]
(Originally: Prevent self-evals from being submitted past their deadline)

ccis: blerner commented on Nov 22, 2016

Especially if the student is taking a late day... The UI should pop up an alert giving a countdown until the deadline, or something, to make it clear. (We had a student this semester start the self-eval before the late deadline, and finish six minutes after it, which caused the server to think it was two days late, when only a single day was permitted...)

ccis: blerner commented on Feb 10

Partially fixed by 110383f. This may be a sufficient fix; we'll see in practice.

**Comment by blerner** [comment]
In addition to preventing self-evals from being submitted too late, we need an ability to forcibly and auditably prevent students from resubmitting homeworks after viewing their self-evals, or (generally) prevent students from submitting to one assignment before some other one is complete.  We may also want to support peer-review assignments, which is another form of inter-assignment dependency.

**Comment by blerner** [comment]
This now exists (thanks to #84)
