### ISSUE TITLE
TAPParser error handling is odd

### ISSUE THREAD

**Issue by blerner** [CodeGrade/bottlenose#35]
Your change to tap_parser, on line 59, breaks the error handling I'd set up on line 20, and the exception handlers that were anticipating those parse errors (e.g. in grades_controller line 433).  This broke the rendering of the checker and junit graders, when they tried to deal with busted student input.

If a TAP file is malformed, then it should not successfully parse, in my opinion.  Where do you rely on parsing to always, always succeed, no matter how malformed?  And can we come up with a better, more robust solution that works for both of us?

**Comment by NatTuck** [comment]
I'll have to figure out what the concrete case where this broke things was.

I don't remember if it was an issue with Perl TAP output, or if it was just a case where a test script was printing non-commented info lines.

**Comment by blerner** [comment]
Still an issue, or closeable?
