### ISSUE TITLE
clamp, plural -> builtin

### ISSUE THREAD

**Issue by NatTuck** [CodeGrade/bottlenose#38]
These are both built in methods in ruby 2.4

We should pull out the custom versions.

**Comment by blerner** [comment]
Getting rid of `clamp` is easy.  IIRC, `plural` was built in too, but was not available everywhere that it needed to be.

**Comment by NatTuck** [comment]
Active support has pluralize as a string method now, so

    "fish".pluralize(2) => "fish"
    "cat".plurailize(2) => "cats"

Should work everywhere.

**Comment by blerner** [comment]
Is this done now, with the caveat that there's just the one remaining helper in application_controller.rb that re-exposes the built-in method?

**Comment by NatTuck** [comment]
Sure.
