### ISSUE TITLE
Comment editing occasionally loses data

### ISSUE THREAD

**Issue by blerner** [CodeGrade/bottlenose#57]
It's not quite reproducible, but some graders reported problems entering line comments on homeworks, only to find that that the comment text vanished.  Look into the validation of comments, to see whether they're not getting through for some reason.  (Maybe their generated ids, client-side, weren't good; maybe too many comments happened in the same timeout and so some were dropped?)

**Comment by blerner** [comment]
I think this original problem has been fixed, but this semester my graders reported somehow getting duplicate comments instead. I truly don't understand how that could've happened, though...

**Comment by NatTuck** [comment]
I ran into this as well.
This is a design problem with using AJAX for data submission - better to do a real form submission when "save" is clicked and report errors.

**Comment by blerner** [comment]
It's a trade-off, favoring graders who have flaky wifi, or who have to pause grading and come back to it later, without causing them to lose their work. And *that* has bitten enough graders to warrant their complaining about it in the past. This should be no harder to solve than auto saving is elsewhere -- not easy, perhaps, but not insurmountable. I can see several approaches here, and I'll look into it more this summer.

**Comment by blerner** [comment]
I'm pretty sure this has been fixed by https://github.com/blerner/bottlenose/commit/b138150d2f14ea8cafc8ec7d211dd39d272aa32d
