### ISSUE TITLE
Add exam grade release button?

### ISSUE THREAD

**Issue by xingyif** [CodeGrade/bottlenose#69]
Restrict the students from seeing the exam grades when the instructor first entered them.
Release all the grades when the button is clicked.

**Comment by xingyif** [comment]
There is a "Publish Grade" button. But it's only visible after the exam date.

**Comment by blerner** [comment]
True, there is that button...but it's ineffective, since the grades get published as soon as they're entered.  This is a consequence of the way "is grading completed?" is computed, and needs to get fixed.
