### ISSUE TITLE
Get rid of archived terms, but make courses hide-able

### ISSUE THREAD

**Issue by NatTuck** [CodeGrade/bottlenose#7]
Hidden courses should be visible to admins and users registered for that course.

**Comment by blerner** [comment]
Going to close this and merge with #8.  I'll give courses a sunrise and sunset date, outside of which they will not be available for registration requests. For students, a course will be visible iff they are registered for it or if it's currently between the course availability dates. For faculty, courses will always be visible. Faculty in a course can always register new people to the course manually. Terms will be collapsed iff there are no active courses within them.
