### ISSUE TITLE
Remove user email mask

### ISSUE THREAD

**Issue by xingyif** [CodeGrade/bottlenose#76]
User email is shown as user's name<>. Any reason why we can't directly show the email?

![screen shot 2017-07-04 at 13 40 23](https://user-images.githubusercontent.com/15064985/27839326-677ffd4a-60be-11e7-903d-236a234ed6ac.png)

**Comment by blerner** [comment]
Oh, that's amusing!  What's actually happening here is a call to 
```
mail_to "#{@user.name} <#{@user.email}>", @user.email
```
and this particular user has no email address.  When `mail_to` is called with two arguments, it uses the first one as the email address, and the second one as the visible text.  When the second argument is nil, evidently, it uses the first argument for both purposes.  So you're seeing bogus text there.

It's an easy fix; I'll push it in a little while.  Thanks :)

**Comment by xingyif** [comment]
@blerner user's email should never be blank, right?
when creating/editing a user, email should be a required field. we should add this requirement in db, model, controller, and even view

**Comment by blerner** [comment]
In Nat's design, users don't necessarily have emails.

**Comment by NatTuck** [comment]
We lost required email in the move to LDAP, since people can log in without having a known email.
