### ISSUE TITLE
View teams by section

### ISSUE THREAD

**Issue by alexjo2144** [CodeGrade/bottlenose#88]
Currently you can only view the list of all teams registered for a given assignment. Being able to filter that list down to just one section would make it easier for TA's to keep track of the teams they're responsible for, similarly to how the "Student Facebook" page can be filtered via the drop down.

**Comment by blerner** [comment]
Yup.  This needs to happen on the team summary page and on the team-editing page.  Presumably, in the case of split-across-lab-sections teams, the team should show up in all relevant filters?

**Comment by alexjo2144** [comment]
That would make sense to me. Possibly with a visual warning of some sort for those teams to make it obvious which student(s) in the team belongs in the filtered set?

**Comment by blerner** [comment]
This is now done for the teamset editing page; the teamset summary page still isn't filtered yet.
