### ISSUE TITLE
"Dissolve all" dissolves all teams in a teamset without regard to filtered section

### ISSUE THREAD

**Issue by kylesferrazza** [CodeGrade/bottlenose#94]
To reproduce: when editing teams, filter to a specific lab section and click the dissolve all teams button.
Expected result: all teams in the section are dissolved
Actual result: all teams in all sections are dissolved

**Comment by blerner** [comment]
That should *not* be happening: there should be a filtering of the dissolved teams. I'll look into it.

**Comment by blerner** [comment]
When you filter down to a section, does the red button change from "Dissolve all" to "Dissolve all in section"?  It should -- I see that happen on both Firefox and Chrome, so it *ought* to work.  What browser/course/section combination were you trying?

**Comment by kylesferrazza** [comment]
It seems we had used the team *requests* filter and clicked dissolve without using the bottom *active teams* filter - sorry about that

**Comment by blerner** [comment]
If you can think of ways to make this UI clearer or more intuitive, let me know...

**Comment by kylesferrazza** [comment]
Perhaps one filter drop-down at the top that applies to randomizing teams (removes the need for the *match team members:* drop-down), and dissolving teams within the set.
