### ISSUE TITLE
Grade average weights assignments with null grades before due date as zeroes

### ISSUE THREAD

**Issue by FletcherTime** [CodeGrade/bottlenose#99]
In the "Grade so far" section of the assignments page, assignments that have no submissions and whose due dates have not yet past count as zeroes toward the displayed average.

**Comment by blerner** [comment]
Correct.  If you have not yet submitted, but could do so, we assume you won't and count it as a zero.  It's a subtle nudge to get you to submit homeworks :)  Also, it avoids a nasty divide-by-zero edge case that's really hard to avoid any other way.  I went back and forth on this design several times, and this is the least confusing version I could come up with.
